[workspace]
resolver = "3"
members = [
    "constants_and_statics",
    "control_flow", 
    "control_flow_exercise_1_if_else", 
    "control_flow_exercise_2_loop", 
    "control_flow_exercise_3_while", 
    "control_flow_exercise_4_for",
    "functions_exercise_2_return_types",
    "functions_exercise_3_return_keyword", 	
    "functions",
    "hello_world",
    "primitive_data_types",
    "variables", "ownership", "ownership_2", "ownership_exercise_1_moving_on_assignment", "ownership_exercise_2_moving_on_assignment_2", "ownership_exercise_3_moving_into_function", "ownership_exercise_4_moving_out_of_function", "borrowing", "borrowing_exercise_1_immutable_references", "borrowing_exercise_2_mutable_ref", "borrowing_exercise_3_mutable_references_2", "borrowing_exercise_4_passing_by_reference", "slices", "slices_exercise_1_string_slice", "slices_exercise_2_array_slice", "structs", "structs_exercise_1_struct_definition", "structs_exercise_2_mutating_structs", "structs_exercise_3_structs_and_functions", "implementation_blocks", "implementation_blocks_exercise_1_methods", "implementation_blocks_exercise_2_associated_functions", "tuple_structs", "tuple_structs_exercise_1_definition", "enums", "enums_exercise_1_definition_1", "enums_exercise_2_definition_2", "enums_2", "matching", "matching_exercise_1_exhaustive_requirement", "matching_exercise_2_match_expression", "matching_exercise_3_matching_on_enums_1", "matching_exercise_4_matching_on_enums_2",
    ]

